Resources:
    EmployeesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:provider.stage}-${self:service}-employees
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
